project_id = "itxpdoppymvbotsiutea"

[functions]
  [functions.analyze-item]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.calendar-feed]
    verify_jwt = false
  [functions.scan-receipt]
    verify_jwt = false
