// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-lists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/_helpers.ts
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Nicht angemeldet. Bitte verbinde dich erneut \xFCber OAuth." }],
    isError: true
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(text, structuredContent) {
  return { content: [{ type: "text", text }], ...structuredContent ? { structuredContent } : {} };
}

// src/lib/mcp/tools/list-lists.ts
var list_lists_default = defineTool({
  name: "list_shopping_lists",
  title: "Einkaufslisten auflisten",
  description: "Listet alle Einkaufslisten der angemeldeten Person mit Anzahl offener Artikel auf.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lists").select("id, name, updated_at, items(id, is_checked)").order("updated_at", { ascending: false });
    if (error) return fail(error.message);
    const lists = (data ?? []).map((l) => ({
      id: l.id,
      name: l.name,
      updated_at: l.updated_at,
      open_items: (l.items ?? []).filter((i) => !i.is_checked).length,
      total_items: (l.items ?? []).length
    }));
    return ok(JSON.stringify(lists, null, 2), { lists });
  }
});

// src/lib/mcp/tools/list-items.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_items_default = defineTool2({
  name: "list_items",
  title: "Artikel einer Liste",
  description: "Zeigt die Artikel einer Einkaufsliste, optional nur offene oder nur abgehakte.",
  inputSchema: {
    list_id: z.string().uuid().describe("ID der Einkaufsliste (aus list_shopping_lists)."),
    status: z.enum(["alle", "offen", "abgehakt"]).default("offen").describe("Filter nach Status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ list_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("items").select("id, name, menge, einheit, kategorie, is_checked, ablauf_datum, preis").eq("list_id", list_id).order("created_at", { ascending: true });
    if (status === "offen") query = query.eq("is_checked", false);
    if (status === "abgehakt") query = query.eq("is_checked", true);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok(JSON.stringify(data ?? [], null, 2), { items: data ?? [] });
  }
});

// src/lib/mcp/tools/add-item.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var add_item_default = defineTool3({
  name: "add_item",
  title: "Artikel hinzuf\xFCgen",
  description: "F\xFCgt einer Einkaufsliste einen neuen Artikel hinzu.",
  inputSchema: {
    list_id: z2.string().uuid().describe("ID der Einkaufsliste."),
    name: z2.string().trim().min(1).describe("Name des Artikels, z. B. 'Milch'."),
    menge: z2.number().positive().optional().describe("Menge, z. B. 2."),
    einheit: z2.string().trim().optional().describe("Einheit, z. B. 'St\xFCck', 'g', 'l'."),
    kategorie: z2.string().trim().optional().describe("Kategorie, z. B. 'Milchprodukte'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ list_id, name, menge, einheit, kategorie }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("items").insert({ list_id, user_id: ctx.getUserId(), name, menge: menge ?? null, einheit: einheit ?? null, kategorie: kategorie ?? null }).select("id, name, menge, einheit, kategorie").single();
    if (error) return fail(error.message);
    return ok(`Hinzugef\xFCgt: ${data.name}`, { item: data });
  }
});

// src/lib/mcp/tools/check-item.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var check_item_default = defineTool4({
  name: "check_item",
  title: "Artikel abhaken",
  description: "Hakt einen Artikel ab (wandert damit in den Vorrat) oder macht das Abhaken r\xFCckg\xE4ngig.",
  inputSchema: {
    item_id: z3.string().uuid().describe("ID des Artikels."),
    checked: z3.boolean().default(true).describe("true = abhaken, false = zur\xFCck auf die Liste.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ item_id, checked }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("items").update({ is_checked: checked, checked_at: checked ? (/* @__PURE__ */ new Date()).toISOString() : null }).eq("id", item_id).select("id, name, is_checked, ablauf_datum").single();
    if (error) return fail(error.message);
    return ok(`${data.name} ist jetzt ${data.is_checked ? "abgehakt" : "wieder offen"}.`, { item: data });
  }
});

// src/lib/mcp/tools/pantry-status.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var pantry_status_default = defineTool5({
  name: "pantry_status",
  title: "Vorrat & Ablaufdaten",
  description: "Zeigt den aktuellen Vorrat (abgehakte Artikel) sortiert nach Ablaufdatum \u2013 ideal f\xFCr 'Was l\xE4uft bald ab?'.",
  inputSchema: {
    tage: z4.number().int().min(1).max(90).default(7).describe("Nur Artikel, die in den n\xE4chsten X Tagen ablaufen.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tage }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const limit = new Date(Date.now() + tage * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("items").select("id, name, kategorie, ablauf_datum, lagerhinweis").eq("is_checked", true).not("ablauf_datum", "is", null).lte("ablauf_datum", limit).order("ablauf_datum", { ascending: true });
    if (error) return fail(error.message);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const items = (data ?? []).map((i) => ({
      ...i,
      status: i.ablauf_datum < today ? "abgelaufen" : "l\xE4uft bald ab"
    }));
    return ok(JSON.stringify(items, null, 2), { items });
  }
});

// src/lib/mcp/tools/create-list.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_list_default = defineTool6({
  name: "create_shopping_list",
  title: "Einkaufsliste erstellen",
  description: "Erstellt eine neue Einkaufsliste f\xFCr die angemeldete Person.",
  inputSchema: { name: z5.string().trim().min(1).describe("Name der Liste, z. B. 'Wocheneinkauf'.") },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("lists").insert({ name, user_id: ctx.getUserId() }).select("id, name").single();
    if (error) return fail(error.message);
    return ok(`Liste "${data.name}" erstellt (${data.id}).`, { list: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "itxpdoppymvbotsiutea";
var mcp_default = defineMcp({
  name: "goodgoods-ai-deine-ki-gest-tzte-einkaufsliste",
  title: "GoodGoods AI - Deine KI-gest\xFCtzte Einkaufsliste",
  version: "0.1.0",
  instructions: "Tools f\xFCr GoodGoods, eine smarte Einkaufsliste mit Vorratsverwaltung gegen Foodwaste. Nutze list_shopping_lists, um Listen zu finden, list_items f\xFCr deren Artikel, add_item und create_shopping_list zum Anlegen, check_item zum Abhaken (abgehakte Artikel wandern in den Vorrat) und pantry_status f\xFCr Lebensmittel, die bald ablaufen.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_lists_default, list_items_default, create_list_default, add_item_default, check_item_default, pantry_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
